version: '3.8'

services:
  db:
    image: mysql:8.0.40
    container_name: app_dev_db
    environment:
      MYSQL_ROOT_PASSWORD: app_dev # Set the root password here
      MYSQL_DATABASE: app_dev # Set the database name here
    ports:
      - '3306:3306'
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
